---
name: Compatibility Issue
description: ATBC is not compatible with your setup
title: "Replace With Title"
labels: ["compatibility"]
body:
    - type: textarea
      id: description
      attributes:
          label: Description
          description: Describe the compatibility issue.
      validations:
          required: true

---

