name: Bump Version

on:
    workflow_dispatch:
        inputs:
            version:
                description: "Version of the next production release (e.g., 1.0.0)"
                required: true
                type: string

jobs:
    run:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v6
              with:
                  ref: ${{ github.ref }}
                  token: ${{ secrets.ADMIN_PAT }}
            - name: Setup Node.js Environment
              uses: actions/setup-node@v6
              with:
                  node-version: 24
            - name: Validate Format And Bump Version
              run: |
                  if ! [[ "${{ inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then \
                      echo "Error: Expects version format (X.Y.Z)."; \
                      exit 1; \
                  fi
                  git checkout -b bump/v${{ inputs.version }}
                  npm version "${{ inputs.version }}" --no-git-tag-version
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git add package.json
                  if [ -f package-lock.json ]; then \
                      git add package-lock.json; \
                  fi
                  git commit -m "bump: bump version to ${{ inputs.version }}"
                  git push origin bump/v${{ inputs.version }}
            - name: Create And Merge Pull Request
              env:
                  GH_TOKEN: ${{ secrets.ADMIN_PAT }}
              run: |
                  gh pr create \
                      --title "Bump version to ${{ inputs.version }}" \
                      --body "Automated version bump to ${{ inputs.version }}" \
                      --head bump/v${{ inputs.version }} \
                      --base main
                  gh pr merge bump/v${{ inputs.version }} \
                      --admin \
                      --merge \
                      --delete-branch
