name: Bump Version

on:
    workflow_dispatch:
        inputs:
            version:
                description:
                    Version of the next production release (e.g., 1.0.0)
                required: true
                type: string

jobs:
    run:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v6
              with:
                  ref: ${{ github.ref }}
                  token: ${{ secrets.ADMIN_PAT }}
            - name: Setup Node.js Environment
              uses: actions/setup-node@v6
              with:
                  node-version: 24
            - name: Validate Format And Bump Version
              run:
                  bash scripts/utils.sh bump_package_version "${{
                  inputs.version}}"
            - name: Create And Merge Pull Request
              env:
                  GH_TOKEN: ${{ secrets.ADMIN_PAT }}
              run:
                  bash scripts/utils.sh create_and_merge_pr "${{
                  inputs.version}}"
