name: Release Production

on:
    workflow_dispatch:
        inputs:
            notes:
                description: Release notes for the release
                required: false
                type: string

jobs:
    run:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v6
              with:
                  ref: ${{ github.ref }}
            - name: Setup Node.js Environment
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: npm
            - name: Prepare Environment And Metadata
              id: version
              run:
                  bash scripts/utils.sh prepare_production_metadata "${{
                  inputs.notes }}"
            - name: Build And Upload To AMO (Production)
              env:
                  FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
                  FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
              run: bash scripts/utils.sh build_and_sign_production
            - name: Tag And Create GitHub Release
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run:
                  bash scripts/utils.sh create_production_release "${{
                  steps.version.outputs.version }}" "${{ inputs.notes }}"
