name: Release Beta

on:
    workflow_dispatch:

jobs:
    run:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v6
              with:
                  ref: ${{ github.ref }}
                  fetch-depth: 0
            - name: Setup Node.js Environment
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: npm
            - name: Install Dependencies And Prepare Version
              id: version
              run: bash scripts/utils.sh prepare_beta_version
            - name: Build And Upload To AMO (Beta)
              env:
                  FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
                  FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
              run:
                  bash scripts/utils.sh build_and_sign_beta "${{
                  steps.version.outputs.beta_version }}"
            - name: Tag And Create GitHub Pre-release
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run:
                  bash scripts/utils.sh create_beta_release "${{
                  steps.version.outputs.beta_tag }}" "${{
                  steps.version.outputs.beta_version }}"
