name: Release Production

on:
    workflow_dispatch:
        inputs:
            notes:
                description: "Release notes for the release"
                required: false
                type: string

jobs:
    run:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v6
              with:
                  ref: ${{ github.ref }}
            - name: Setup Node.js Environment
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: "npm"
            - name: Prepare Environment And Metadata
              id: version
              run: |
                  npm ci
                  BASE_VERSION=$(node -p "require('./package.json').version")
                  echo "version=$BASE_VERSION" >> "$GITHUB_OUTPUT"
                  jq -n --arg notes "${{ inputs.notes }}" \
                      '{"version": {"release_notes": {"en-GB": $notes}}}' \
                      > amo_metadata.json
            - name: Build And Upload To AMO (Production)
              env:
                  FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
                  FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
              run: |
                  npm run zip
                  npx web-ext sign \
                      --api-key $FIREFOX_JWT_ISSUER \
                      --api-secret $FIREFOX_JWT_SECRET \
                      --channel listed \
                      --source-dir .output/atbc \
                      --upload-source-code .output/atbc-sources.zip \
                      --amo-metadata amo_metadata.json \
                      --approval-timeout 0
            - name: Tag And Create GitHub Release
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git tag v${{ steps.version.outputs.version }}
                  git push origin v${{ steps.version.outputs.version }}
                  gh release create "v${{ steps.version.outputs.version }}" \
                      --title "v${{ steps.version.outputs.version }}" \
                      --notes "${{ inputs.notes }}"
